### PR TITLE
remove controller runtime dependency

### PR DESCRIPTION
**Pull request by Madhu-1**
# Describe what this PR does #

we have seen the issues in other projects where API has controller runtime as a dependency though the main project importing the operator doesn't have the dependency on controller runtime directly now they need to wait for it to update to other kubernetes versions as well.

https://github.com/ceph/ceph-csi-operator/pull/94#issuecomment-2272512200

### CODE REVIEW

**Comment by Madhu-1** [comment]
@leelavg ^^

**Comment by Madhu-1** [comment]
If all agree on this one, am going to test it later

**Comment by leelavg** [comment]
> @leelavg ^^
- able to build client-op w/ these changes. thanks.

**Review by nb-ohad — APPROVED** [review]

**Comment by nb-ohad** [comment]
I would suggest having a different approach here. We can create our own interface on top of Register and use it inside the API Package.

The can be considered for the future

**Pull request merged**
