### PR TITLE
ci: skip config folder from running codespell ci

### PR DESCRIPTION
**Pull request by subhamkrai**
# Describe what this PR does #

config folder are auto generated and there is no need to
run codespell on auto generated files.

**Checklist:**

* [ ] **Commit Message Formatting**: Commit titles and messages follow
  guidelines in the [developer
  guide](https://github.com/ceph/ceph-csi-operator/blob/devel/docs/development-guide.md#commit-messages).
* [ ] Reviewed the developer guide on [Submitting a Pull
  Request](https://github.com/ceph/ceph-csi-operator/blob/devel/docs/development-guide.md#development-workflow)
* [ ] [Pending release
  notes](https://github.com/ceph/ceph-csi-operator/blob/devel/PendingReleaseNotes.md)
  updated with breaking and/or notable changes for the next major release.
* [ ] Documentation has been updated, if necessary.
* [ ] Unit tests have been added, if necessary.
* [ ] Integration tests have been added, if necessary.

### CODE REVIEW

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
@subhamkrai please update the PR description and commit about why this change is requried.

**Comment by subhamkrai** [comment]
> @subhamkrai please update the PR description and commit about why this change is requried.

done

**Comment by Madhu-1** [comment]
>config folder are auto generated and there is no need to run codespell on auto generated files.

Is this true, i know that we also edit these files manually isn't it true (i think we update the sample with an example yaml)?

**Comment by subhamkrai** [comment]
> > config folder are auto generated and there is no need to run codespell on auto generated files.
> 
> Is this true, i know that we also edit these files manually isn't it true (i think we update the sample with an example yaml)?

I got the knowledge from @nb-ohad

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
