### PR TITLE
Driver Controller: Ensure CSI Config Creation

### PR DESCRIPTION
**Pull request by nb-ohad**
# Describe what this PR does #

If a driver CR exists but no client profile CR exists, any container that needs to mount the `ceph-csi-config` config map will fail. To solve the issue, the following behavior is added:

- Driver controller creates an empty `ceph-csi-config` config map if not already exist and adds an owner ref
- Driver controller watch for delete events for `ceph-csi-config` config map

### CODE REVIEW

**Comment by nb-ohad** [comment]
/hold

This PR is rebased on top of #103 and should not be merged until #103 is merged

**Comment by Madhu-1** [comment]
> * Driver controller creates an empty `ceph-csi-config` config map if not already exist and adds an owner ref
> * Driver controller watch for delete events for `ceph-csi-config` config map

Instead of watching for delete events can't we add the driver as the ownerRef if the configmap already exists and we don't need to consider delete events?

**Comment by nb-ohad** [comment]
/unhold

#103 merged, @Madhu-1 can you please add this to your review queue?

**Comment by nb-ohad** [comment]
> > * Driver controller creates an empty `ceph-csi-config` config map if not already exist and adds an owner ref
> > * Driver controller watch for delete events for `ceph-csi-config` config map
> 
> Instead of watching for delete events can't we add the driver as the ownerRef if the configmap already exists and we don't need to consider delete events?

We are already adding the driver as an owner ref. But there is still a need to watch for delete events for the case where the configmap goes away and need to be recreated. The delete filter makes sure that  we are not queuing an based on create or update events

**Comment by Madhu-1** [comment]
> > > * Driver controller creates an empty `ceph-csi-config` config map if not already exist and adds an owner ref
> > > * Driver controller watch for delete events for `ceph-csi-config` config map
> > 
> > 
> > Instead of watching for delete events can't we add the driver as the ownerRef if the configmap already exists and we don't need to consider delete events?
> 
> We are already adding the driver as an owner ref. But there is still a need to watch for delete events for the case where the configmap goes away and need to be recreated. The delete filter makes sure that we are not queuing an based on create or update events

Sorry am failing to understand it as we are adding the owner ref if the configmap already exists how it will go away if the driver is not deleted? Do you mean the use will manually remove the configmap by hand?

**Comment by nb-ohad** [comment]
Yes.
It can be faulty code in external automation, or some bug in rook or client, or a mistake by an admin, or someone just overwrote the entire ownerRef section instead of adding to it. 

If a controller takes the responsibility to move a system toward a certain actual state it also needs to take the responsibility to readjust if that actual state has changed (for any reason)

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
