### PR TITLE
Driver API: Align type code to established order and rename LogRotation field to Rotation

### PR DESCRIPTION
**Pull request by nb-ohad**
# Describe what this PR does #
- Reorder type definition to the established conversions (definition before usage)
-  Add missing newlines above field descriptions
-  Rename `LogRotation` field to `Rotation`
- Keep resource definition for Plugin container (main container) as the last on the list

## Is there anything that requires special attention ##
no

### CODE REVIEW

**Comment by nb-ohad** [comment]
@parth-gr I could not add you as a reviewer so I am tagging you here in a comment.
Please take a look at the changes

**Review by Madhu-1 — CHANGES_REQUESTED** [review]
Please update the same in design doc as well https://github.com/ceph/ceph-csi-operator/tree/main/docs/design

**Comment by parth-gr** [comment]
Yaa nit, to update the design doc.

**Comment by nb-ohad** [comment]
@Madhu-1 @parth-gr 
Pushed an update to the doc

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
